name: Publish release on push
on:
  push:
    branches:
      - 'mozilla-xpi'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint:js

      - name: Build
        run: npm run build        

      - name: Update GitHub prerelease
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: mozilla-latest
          prerelease: true
          title: "Latest Build"
          files: |
            ./web-ext-artifacts/firefox_translations.xpi
